Update QA.yml

diff --git a/.github/workflows/QA.yml b/.github/workflows/QA.yml
--- a/.github/workflows/QA.yml
+++ b/.github/workflows/QA.yml
@@ -124,9 +124,19 @@ jobs:
             - name: echoing the ouptput
               id: vars8
               run: |
-               finalist= $(cat comm -23 groupedClassesnames.txt wrapper2.txt) 
-               echo $finalist
-              
+               echo $(comm -23 groupedClassesnames.txt wrapper2.txt | tr ' ' '\n' ) >> finalist.txt
+               VER=$(cat finalist.txt)
+               echo "finalist=$VER" >> $GITHUB_ENV
+               
+            - name: succeed the job
+              if: ${{env.finalist = ' ' }
+              run : |
+                 echo "dont exceed the job"
 
+            - name: fail the job
+              if: ${{env.finalist != ' ' }
+              run : |
+                 echo "fail the job"
+                 exit 1
             
             
